---
image: "yuriiashutkin/web-app:1.7.1-scratch"
servicePort: 4000
podPort: 8080
podListenAddress: "0.0.0.0"
serviceAccountName: webapp

secretsDirs: "/vault/secrets"

securityContext:
  runAsGroup: 2000
  runAsUser: 2000
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 32Mi

ingress:
  enabled: false
  domainName: webapp.domain.local

extraAnnotations: {}

csi:
  enabled: false
