---
image: "yuriiashutkin/web-app:1.7.1-scratch"
servicePort: 4000
podPort: 8080
podListenAddress: "0.0.0.0"
serviceAccountName: webapp

secretsDirs: "/vault/secrets"

securityContext:
  runAsGroup: 2000
  runAsUser: 2000
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 32Mi

ingress:
  enabled: false
  domainName: webapp.domain.local

annotations: {}

csi:
  enabled: false
  vaultAddr: http://vault.vault.svc:8200
  roleName: webapp
  secretName: project-kv
  secretProviderClassName: project-kv-secret
  secrets:
    - name: csi-provider-secret
      vaultPath: project-kv/data/secret
      key: value
    - name: csi-provider-secret-v1
      secretFieldName: csi-secret-v1
      vaultPath: project-kv/data/secret?version=1
      key: value
