---
apiVersion: v1
kind: Service
metadata:
  name: summary
  namespace: yaobank
  labels:
    app: summary
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8000
  selector:
    app: summary
