---
# Exec goal without arguments
- id: target
  execute-command: make
  pass-arguments-to-command:
    - source: url
      name: name
  trigger-rule:
    match:
      type: value
      value: "{{ getenv "WEBHOOK_SECRET" | js }}"
      parameter:
        source: header
        name: X-Webhook-Secret
  incoming-payload-content-type: application/json
  include-command-output-in-response: true
  include-command-output-in-response-on-error: true

# Exec goal with args
- id: target-args
  execute-command: make
  pass-arguments-to-command:
    - source: url
      name: name
    - source: payload
      name: args
  trigger-rule:
    match:
      type: value
      value: "{{ getenv "WEBHOOK_SECRET" | js }}"
      parameter:
        source: header
        name: X-Webhook-Secret
  incoming-payload-content-type: application/json
  include-command-output-in-response: true
  include-command-output-in-response-on-error: true
