---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        revision: {{ .Release.Revision | quote }}
        {{- .Values.annotations | toYaml | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: webapp
          image: {{ $.Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.podPort }}
          securityContext:
            {{- $.Values.securityContext | toYaml | nindent 12 }}
          resources:
            {{- $.Values.resources | toYaml | nindent 12 }}
          env:
            - name: LISTEN_ADDR
              value: "{{ $.Values.podListenAddress }}:{{ $.Values.podPort }}"
            - name: SECRETS_DIRS
              value: {{ .Values.secretsDirs }}
      {{- if .Values.csi.enabled }}
            {{- range $secret := .Values.csi.secrets }}
            - name: "FROM_VAULT_{{ $secret.secretFieldName | default $secret.name }}"
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.csi.secretName }}
                  key: {{ $secret.secretFieldName | default $secret.name }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.csi.secretName | quote }}
              mountPath: "/mnt/{{ .Values.csi.secretName }}"
              readOnly: true
      volumes:
        - name: {{ .Values.csi.secretName | quote }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.csi.secretProviderClassName | quote }}
      {{- end }}
