---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        revision: {{ $.Release.Revision | quote }}
        {{- .Values.extraAnnotations | toYaml | nindent 8 }}
    spec:
      containers:
        - name: webapp
          image: {{ $.Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.podPort }}
          securityContext:
            {{- $.Values.securityContext | toYaml | nindent 12 }}
          resources:
            {{- $.Values.resources | toYaml | nindent 12 }}
          env:
            - name: LISTEN_ADDR
              value: "{{ $.Values.podListenAddress }}:{{ $.Values.podPort }}"
            - name: SECRETS_DIRS
              value: {{ .Values.secretsDirs }}
            {{- if .Values.csi.enabled }}
            - name: FROM_VAULT_K8S_SECRET_FROM_CSI
              valueFrom:
                secretKeyRef:
                  name: project-kv-secret
                  key: project-kv-secret
            - name: FROM_VAULT_K8S_SECRET_FROM_CSI_V1
              valueFrom:
                secretKeyRef:
                  name: project-kv-secret
                  key: project-kv-secret-v1
            {{- end }}
          {{- if .Values.csi.enabled }}
          volumeMounts:
            - name: project-kv-secret
              mountPath: "/mnt/project-kv-secret"
              readOnly: true
          {{- end  }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if .Values.csi.enabled }}
      volumes:
        - name: project-kv-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "project-kv-secret"
      {{- end }}
