{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
spec:
  ingressClassName: contour
  rules:
    - host: {{ $.Values.domainName }}
      http:
        paths:
          - backend:
              service:
                name: webapp
                port:
                  number: {{ .Values.servicePort }}
            path: /
            pathType: Prefix

{{- end }}
