{{- if .Values.csi.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.secretProviderClassName | quote }}
spec:
  provider: vault
  secretObjects:
    - data:
        {{- range $secret := .Values.csi.secrets }}
        - key: {{ $secret.secretFieldName | default $secret.name | quote }}
          objectName: {{ $secret.secretFieldName | default $secret.name | quote }}
        {{- end }}
      secretName: {{ .Values.csi.secretName }}
      type: Opaque
  parameters:
    vaultAddress: {{ .Values.csi.vaultAddr }}
    roleName: {{ .Values.csi.roleName }}
    objects: |
      {{- range $secret := .Values.csi.secrets }}
      - objectName: {{ $secret.secretFieldName | default $secret.name | quote }}
        secretPath: {{ $secret.vaultPath | quote }}
        secretKey: {{ $secret.key | quote }}
      {{- end }}

{{- end }}
