---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $.Values.servicePort }}
      targetPort: {{ $.Values.podPort }}
